data_treatments = [
    {"kode_pengobatan": "PN01", "pengobatan": "Perawatan fluoride dapat membantu remineralisasi enamel gigi apabila kerusakan gigi belum parah"},
    {"kode_pengobatan": "PN02", "pengobatan": "Melakukan tambal gigi apabila kerusakan gigi belum terlalu dalam"},
    {"kode_pengobatan": "PN03", "pengobatan": "Perawatan saluran akar ketika kerusakan gigi sudah mencapai bagian pulpa/syaraf gigi"},
    {"kode_pengobatan": "PN04", "pengobatan": "Perawatan mahkota gigi apabila permukaan kerusakan gigi sudah luas"},
    {"kode_pengobatan": "PN05", "pengobatan": "Pencabutan gigi apabila kerusakan sudah sangat parah dan tidak dapat diatasi dengan perawatan lain"},
    {"kode_pengobatan": "PN06", "pengobatan": "Drainase/pengeluaran pus/nanah melalui poket periodontal"},
    {"kode_pengobatan": "PN07", "pengobatan": "Drainase/pengeluaran pus/nanah melalui insisi abses"},
    {"kode_pengobatan": "PN08", "pengobatan": "Melakukan tindakan scaling dan root planing pada area gigi yang terkena abses"},
    {"kode_pengobatan": "PN09", "pengobatan": "Pemberian antibiotik apabila diperlukan tergantung tingkat keparahan infeksi"},
    {"kode_pengobatan": "PN10", "pengobatan": "Drainase/pengeluaran pus/nanah pada saluran akar atau melalui insisi abses"},
    {"kode_pengobatan": "PN11", "pengobatan": "Perawatan saluran akar untuk menghilangkan infeksi dan mempertahankan gigi"},
    {"kode_pengobatan": "PN12", "pengobatan": "Tindakan pencabutan gigi apabila gigi yang terkena tidak dapat diselamatkan"},
    {"kode_pengobatan": "PN13", "pengobatan": "Menggunakan pasta gigi khusus untuk gigi sensitif"},
    {"kode_pengobatan": "PN14", "pengobatan": "Aplikasi bahan atau senyawa yang bisa melapisi dan menutup pori pada dentin (agen desensitisasi)"},
    {"kode_pengobatan": "PN15", "pengobatan": "Tindakan tambal gigi untuk mengatasi gigi sensitif"},
    {"kode_pengobatan": "PN16", "pengobatan": "Prosedur bedah ringan berupa cangkok gusi dapat mengembalikan gusi yang turun"},
    {"kode_pengobatan": "PN17", "pengobatan": "Tindakan cabut gigi apabila gigi sudah terlihat di permukaan gusi"},
    {"kode_pengobatan": "PN18", "pengobatan": "Operasi cabut gigi bungsu apabila impaksi gigi terjadi menyeluruh/tidak terlihat di permukaan gigi"},
    {"kode_pengobatan": "PN19", "pengobatan": "Perawatan dengan kawat gigi untuk memperbaiki posisi gigi"},
    {"kode_pengobatan": "PN20", "pengobatan": "Pencabutan satu atau lebih gigi apabila maloklusi disebabkan oleh kepadatan gigi"},
    {"kode_pengobatan": "PN21", "pengobatan": "Menggunakan perangkat gigi atau retainer gigi untuk menyusun gigi kembali"},
    {"kode_pengobatan": "PN22", "pengobatan": "Melakukan perbaikan pada gigi yang mengalami gangguan atau yang tidak normal"},
    {"kode_pengobatan": "PN23", "pengobatan": "Melakukan pembedahan untuk membentuk, memperpendek, dan menstabilkan tulang rahang apabila diperlukan"},
    {"kode_pengobatan": "PN24", "pengobatan": "Menyikat gigi secara teratur dengan sikat berbulu lembut secara perlahan"},
    {"kode_pengobatan": "PN25", "pengobatan": "Rutin berkumur dengan obat kumur antiseptik"},
    {"kode_pengobatan": "PN26", "pengobatan": "Mengurangi keluhan nyeri dengan menggunakan obat salep penghilang rasa sakit"},
    {"kode_pengobatan": "PN27", "pengobatan": "Hindari makanan yang asam, pedas dan keras"},
    {"kode_pengobatan": "PN28", "pengobatan": "Konsumsi cairan ekstra untuk mengimbangi mulut kering"},
    {"kode_pengobatan": "PN29", "pengobatan": "Tindakan scaling gigi untuk membersihkan plak dan karang gigi yang menempel pada gusi"},
    {"kode_pengobatan": "PN30", "pengobatan": "Tindakan root planing apabila sudah mengalami penyakit gusi atau periodontitis"},
    {"kode_pengobatan": "PN31", "pengobatan": "Operasi flap  dilakukan untuk mengangkat plak dan karang gigi dari kantong gusi"},
    {"kode_pengobatan": "PN32", "pengobatan": "Penggunaan obat kumur chlorhexidine 0,2%"},
    {"kode_pengobatan": "PN33", "pengobatan": "Penggunaan obat kortikosteroid topikal (triamcinolone in orbase) untuk mengurangi rasa sakit"},
    {"kode_pengobatan": "PN34", "pengobatan": "Terapi suportif berupa pemberian multivitamin B-complex, A,C,E dan Zinc"},
    {"kode_pengobatan": "PN35", "pengobatan": "Menjaga kebersihan rongga mulut"},
    {"kode_pengobatan": "PN36", "pengobatan": "Menjaga pola makan dengan gizi seimbang"}
]

data_preventions=[
    {"kode_pencegahan": "PG01", "pencegahan": "Membersihkan gigi dengan sikat dan benang gigi, minimal 2x sehari"},
    {"kode_pencegahan": "PG02", "pencegahan": "Menggunakan pasta gigi yang mengandung fluoride"},
    {"kode_pencegahan": "PG03", "pencegahan": "Membatasi konsumsi makanan dan minuman manis"},
    {"kode_pencegahan": "PG04", "pencegahan": "Berkumur dengan obat kumur antiseptik"},
    {"kode_pencegahan": "PG05", "pencegahan": "Melakukan pemeriksaan gigi secara rutin setidaknya 6 bulan sekali"},
    {"kode_pencegahan": "PG06", "pencegahan": "Sikat gigi 2x sehari dengan pasta gigi yang mengandung fluoride"},
    {"kode_pencegahan": "PG07", "pencegahan": "Menggunakan benang gigi atau dental floss untuk membersihkan sela gigi setiap hari"},
    {"kode_pencegahan": "PG08", "pencegahan": "Rutin berkumur dengan obat kumur antiseptik"},
    {"kode_pencegahan": "PG09", "pencegahan": "Menyikat gigi dengan sikat gigi yang halus dan lembut dan menggunakan pasta gigi mengandung fluoride"},
    {"kode_pencegahan": "PG10", "pencegahan": "Menyikat gigi secara perlahan/tidak menggunakan tekanan yang terlalu kuat"},
    {"kode_pencegahan": "PG11", "pencegahan": "Membatasi konsumsi makanan dan minuman yang terlalu asam, manis, panas, dingin"},
    {"kode_pencegahan": "PG12", "pencegahan": "Gerakan sikat gigi menyapu dari arah gusi ke gigi"},
    {"kode_pencegahan": "PG13", "pencegahan": "Segera lakukan pemeriksaan ke dokter apabila timbul gejala impaksi gigi"},
    {"kode_pencegahan": "PG14", "pencegahan": "Lakukan pemeriksaan gigi dan mulut sedini mungkin terutama ketika gigi sudah mulai tumbuh"},
    {"kode_pencegahan": "PG15", "pencegahan": "Mencegah kebiasaan buruk yang dapat menyebabkan maloklusi gigi"},
    {"kode_pencegahan": "PG16", "pencegahan": "Memberhentikan kebiasaan buruk sedini mungkin agar maloklusi gigi tidak bertambah parah"},
    {"kode_pencegahan": "PG17", "pencegahan": "Melakukan perawatan sedini mungkin apabila sudah terjadi maloklusi agar tidak memperparah maloklusi"},
    {"kode_pencegahan": "PG18", "pencegahan": "Menyikat gigi secara teratur dengan sikat berbulu lembut secara perlahan"},
    {"kode_pencegahan": "PG19", "pencegahan": "Konsumsi cairan ekstra untuk mengimbangi mulut kering"},
    {"kode_pencegahan": "PG20", "pencegahan": "Menjaga pola makan dengan gizi seimbang"},
    {"kode_pencegahan": "PG21", "pencegahan": "Menjaga kebersihan rongga mulut"},
    {"kode_pencegahan": "PG22", "pencegahan": "Menghindari faktor predisposisi stomatitis aftosa (defisiensi vitamin, stres, alergi, imun, trauma)"}
]

data_symptoms = [
    {"kode_gejala": "G01", "gejala": "Lubang yang terlihat pada gigi", "bobot": 5},
    {"kode_gejala": "G02", "gejala": "Noda berwarna coklat kehitaman yang terdapat pada permukaan gigi", "bobot": 3},
    {"kode_gejala": "G03", "gejala": "Riwayat nyeri saat mengonsumsi makanan manis/panas/dingin atau saat makanan masuk/menyangkut", "bobot": 5},
    {"kode_gejala": "G04", "gejala": "Gigi terasa ngilu dan lebih sensitif", "bobot": 5},
    {"kode_gejala": "G05", "gejala": "Bau mulut yang tidak sedap", "bobot": 1},
    {"kode_gejala": "G06", "gejala": "Pembengkakan gusi di bagian samping disertai nanah", "bobot": 5},
    {"kode_gejala": "G07", "gejala": "Gusi kemerahan", "bobot": 3},
    {"kode_gejala": "G08", "gejala": "Salah satu gigi yang terlibat mengalami kegoyangan", "bobot": 3},
    {"kode_gejala": "G09", "gejala": "Gigi terasa sakit ketika mengunyah dan timbul rasa nyeri", "bobot": 5},
    {"kode_gejala": "G10", "gejala": "Gusi terasa lunak", "bobot": 3},
    {"kode_gejala": "G11", "gejala": "Terdapat karies gigi", "bobot": 5},
    {"kode_gejala": "G12", "gejala": "Pembengkakan pada bagian akar gigi (bagian dalam gusi) sehingga gigi terasa timbul", "bobot": 5},
    {"kode_gejala": "G13", "gejala": "Sakit gigi ketika diketuk/perkusi", "bobot": 5},
    {"kode_gejala": "G14", "gejala": "Akar gigi yang terekspos (dentin) sensitif terhadap panas dan dingin akibat resesi gusi", "bobot": 5},
    {"kode_gejala": "G15", "gejala": "Terdapat cekungan pada permukaan gigi (dekat gusi bagian enamel) yang berwarna kecoklatan", "bobot": 3},
    {"kode_gejala": "G16", "gejala": "Riwayat cara menyikat gigi yang salah", "bobot": 3},
    {"kode_gejala": "G17", "gejala": "Enamel gigi yang rusak, mengekspos lapisan dalam gigi", "bobot": 3},
    {"kode_gejala": "G18", "gejala": "Gigi tidak terlihat sama sekali atau hanya muncul sedikit di permukaan gusi", "bobot": 5},
    {"kode_gejala": "G19", "gejala": "Gusi bengkak dan kemerahan di sekitar gigi terpendam", "bobot": 5},
    {"kode_gejala": "G20", "gejala": "Nyeri pada rahang dan kesulitan membuka mulut", "bobot": 3},
    {"kode_gejala": "G21", "gejala": "Pembesaran kelenjar getah bening di leher dan sakit ketika ditekan", "bobot": 3},
    {"kode_gejala": "G22", "gejala": "Sakit kepala yang terjadi secara terus menerus", "bobot": 1},
    {"kode_gejala": "G23", "gejala": "Ketidakmampuan untuk menggigit makanan dengan benar (gigitan terbuka)", "bobot": 5},
    {"kode_gejala": "G24", "gejala": "Susunan gigi yang tidak normal", "bobot": 5},
    {"kode_gejala": "G25", "gejala": "Perubahan struktur wajah", "bobot": 3},
    {"kode_gejala": "G26", "gejala": "Kesulitan atau ketidaknyamanan saat menggigit atau mengunyah", "bobot": 5},
    {"kode_gejala": "G27", "gejala": "Gangguan atau kesulitan berbicara", "bobot": 3},
    {"kode_gejala": "G28", "gejala": "Luka atau bercak putih atau kemerahan di dalam mulut dan tenggorokan", "bobot": 5},
    {"kode_gejala": "G29", "gejala": "Kesulitan untuk menelan, makan maupun berbicara", "bobot": 5},
    {"kode_gejala": "G30", "gejala": "Sensasi terbakar atau sakit saat makan maupun minum", "bobot": 3},
    {"kode_gejala": "G31", "gejala": "Mulut dan gusi yang merah, mengkilap, dan bengkak", "bobot": 5},
    {"kode_gejala": "G32", "gejala": "Mulut terasa kering", "bobot": 3},
    {"kode_gejala": "G33", "gejala": "Gusi mudah berdarah saat sikat gigi atau flossing (menggunakan benang dental)", "bobot": 5},
    {"kode_gejala": "G34", "gejala": "Gusi bengkak atau besar karena edema", "bobot": 3},
    {"kode_gejala": "G35", "gejala": "Penumpukan plak dan karang gigi pada gigi", "bobot": 5},
    {"kode_gejala": "G36", "gejala": "Gejala prodormal berupa rasa terbakar dan sakit pada kelenjar limfoid regional/mukosa area sekitar sariawan", "bobot": 3},
    {"kode_gejala": "G37", "gejala": "Luka sariawan berbentuk bulat/oval berwarna putih kekuningan", "bobot": 5},
    {"kode_gejala": "G38", "gejala": "Area luka dikelilingi oleh kemerahan", "bobot": 5},
    {"kode_gejala": "G39", "gejala": "Rasa nyeri pada area luka sariawan", "bobot": 5},
    {"kode_gejala": "G40", "gejala": "Berlangsung selama 7-14 hari dan dapat muncul kembali di lain waktu (rekuren)", "bobot": 3},
]

data_admins = [
    {"email": "20102196@ittelkom-pwt.ac.id", "password": "20102196"},
    {"email": "tiaraputri2172@gmail.com", "password": "Humairaputri21"},
    {"email": "user2024@gmail.com", "password": "user12345"}
]